buildly-release-management/buildly-react-template

src/environments/environment.dev.js
src/pages/Login/Login.js
src/redux/authuser/sagas/authuser.saga.js
src/utils/socialLogin.js

Social Login at the login screen
Allow user to login via social auth

UI changes, Github popup and integrate with BE

---

src/components/InlineEditor/InlineEditor.js
src/components/Modal/Modal.js
src/environments/environment.dev.js
src/layout/Container/Container.js
src/layout/TopBar/TopBar.js
src/pages/Login/Login.js
src/pages/MissingData/MissingData.js
src/pages/UserManagement/UserManagement.js
src/redux/authuser/actions/authuser.actions.js
src/redux/authuser/actions/authuser.actions.test.js
src/redux/authuser/reducers/authuser.reducer.js
src/redux/authuser/reducers/authuser.reducer.test.js
src/redux/authuser/sagas/authuser.saga.js
src/routes/routesConstants.js

Popup for social login users
Show a popup to social login users (for first time) to provide organization and/or email.

Popup social user

---

package.json
src/index.html
webpack.config.js

Fix env to helm issue
Unable to access window environment after moving env to helm charts

Fix issue with moving env to helm chart

---

src/components/SocialLogin/GithubLogin.js
src/components/ToolTip/ToolTip.js
src/pages/Dashboard/components/Kanban.js
src/styles/theme.js

_Updates to Github sign in and styling_
_#23_
closing #23

Updates to Github sign in and styling

---

src/pages/Dashboard/forms/AddFeatures.js
src/pages/Dashboard/forms/AddIssues.js

_Update add feature and add issue forms_
_Select fields of status and feature are populated via BE_
#57

update feature & issue form

---

package.json
src/App.js
src/layout/Container/Container.js
src/layout/TopBar/TopBar.js
src/pages/MissingData/MissingData.js
src/pages/Register/Register.js
src/redux/authuser/reducers/authuser.reducer.js
src/redux/authuser/sagas/authuser.saga.js
src/routes/routesConstants.js

Handle Github Login issues
Make code changes to handle all the registration and GitHub login cases.

Fix github login

---

src/App.js
src/components/Copyright/Copyright.js
src/pages/Home/Home.js
src/routes/Private.route.js
src/routes/routesConstants.js

Landing page
* Create a new Insights landing home page.
* Move login to the bottom nav.
Closes #77

New insights landing page

---

src/pages/Dashboard/components/List.js

Moving extra details of an issue to a popover.
Closes #94.

Adding Popover For Issue Details

---

src/index.js

Adding Google Ad Tag to index.
Closes #96.

Adding Ad Tag.

---

package.json
src/components/StripeCard/StripeCard.js
src/index.js
src/pages/MissingData/MissingData.js
src/pages/Register/Register.js
src/redux/authuser/actions/authuser.actions.js
src/redux/authuser/actions/authuser.actions.test.js
src/redux/authuser/reducers/authuser.reducer.js
src/redux/authuser/reducers/authuser.reducer.test.js
src/redux/authuser/sagas/authuser.saga.js

Allow Stripe integration for subscription
Have the user provide card details whenever new organization is coming in either via registration form or via social login option.
Closes #88

Stripe integration for customer create and get card details

---

src/pages/Dashboard/components/UserDashboard.js
src/pages/Dashboard/forms/AddIssues.js
src/pages/Dashboard/forms/IssueSuggestions.js
src/pages/Dashboard/forms/StatusBoard.js
src/pages/Dashboard/forms/ToolBoard.js
src/redux/product/sagas/product.saga.js

_show select column field when no feat org list_

show select column field when no feat org list

---

.github/workflows/dev-build.yml
.github/workflows/prod-build.yml

- Github actions to create docker image and push it on GCP for master and prod branches.
Ticket number: #120

GitHub action Configuration

---

package.json
src/components/DatePicker/DatePicker.js
src/pages/Dashboard/components/Kanban.js
src/pages/Dashboard/components/UserDashboard.js
src/pages/NewProduct/NewProduct.js
src/pages/NewProduct/components/MinimalFunctionality.js
src/pages/Products/Products.js

_UI changes_
_ If no status column empty hide it
Redirection issue after creating and editing product in products page
feature detail not populating after board configuration, works only on refresh
date picker not showing, package update_
#137

Feat#119/UI changes

---

src/pages/NewProduct/NewProduct.js
src/pages/NewProduct/components/ProductSetup.js
src/redux/product/actions/product.actions.js
src/redux/product/actions/product.actions.test.js
src/redux/product/reducers/product.reducer.js
src/redux/product/reducers/product.reducer.test.js
src/redux/product/sagas/product.saga.js

_ Change current tool to new third party tool
Change Insights[ fresh start] to third party tool
Change current third party tool to Insights[ fresh start]
Validate feature and issue credentials_
#140

change tools before board configuration

---

.github/workflows/prod-build.yml

- Update prod build branch name prod to production

Updated GitHub action branch

---

Dockerfile

specify tag

---

src/pages/Dashboard/components/List.js
src/pages/Dashboard/components/UserDashboard.js
src/redux/decision/sagas/decision.saga.js
src/redux/product/sagas/product.saga.js

_Group issues by its corresponding feature_
#157

group issues by its corresponding feature

---

src/layout/TopBar/TopBar.js
src/pages/Dashboard/components/Kanban.js
src/pages/Dashboard/components/List.js
src/pages/Dashboard/forms/DescribeProcess.js
src/pages/NewProduct/ProductFormConstants.js
src/pages/NewProduct/components/ApplicationMarket.js
src/pages/NewProduct/components/ProductSetup.js

Somes fixes from ticket #172 
* Changes to Product Wizard
* Navigation link for Releases page
* Allow editing logic for features

Fixes from feedback 09/29

---

src/pages/NewProduct/NewProduct.js
src/pages/NewProduct/ProductFormConstants.js
src/pages/NewProduct/components/Setup.js
src/pages/Products/ProductConstants.js

Fix new field issues
Fixes to be done for the following.
* Display complexity, cost in Products table.
* Integration Types field was missing.
* Timezone options were missing.

Fix new field issues

---

src/modules/http/http.service.js
src/pages/Dashboard/components/Kanban.js
src/pages/Dashboard/components/List.js
src/pages/Dashboard/components/UserDashboard.js

Show first few feature suggestions
* Whenever a new product is created, new feature suggestions come from the suggestions table along with the product details.
* Allow users to create or discard suggested features.
* Whenever feature created has suggested issue details in them, these suggested issues will be added to the suggestions generated by ML.
Closes #178

First feature suggestions

---

src/pages/Dashboard/Dashboard.js
src/pages/Dashboard/forms/AddComments.js
src/pages/Dashboard/forms/AddFeatures.js
src/pages/Dashboard/forms/AddIssues.js
src/pages/Dashboard/forms/DescribeProcess.js
src/pages/Dashboard/forms/IgnoreColumns.js
src/pages/Dashboard/forms/IssueSuggestions.js
src/pages/Dashboard/forms/StatusBoard.js
src/pages/Dashboard/forms/ToolBoard.js
src/redux/product/sagas/product.saga.js
src/redux/release/actions/release.actions.js
src/redux/release/actions/release.actions.test.js
src/redux/release/reducers/release.reducer.js
src/redux/release/reducers/release.reducer.test.js
src/redux/release/sagas/release.saga.js

Restore board syncing functionality

Restore Bord Sync Functionality

---

src/pages/Dashboard/Dashboard.js
src/pages/Dashboard/DashboardConstants.js
src/pages/Dashboard/components/Kanban.js
src/pages/Dashboard/components/Tabular.js
src/pages/Dashboard/forms/Comments.js
src/pages/Dashboard/forms/ShowRelatedIssues.js
src/pages/Dashboard/forms/ToolBoard.js
src/pages/MissingData/MissingData.js
src/pages/Register/Register.js
src/redux/release/actions/release.actions.js
src/redux/release/actions/release.actions.test.js
src/redux/release/sagas/release.saga.js
src/routes/routesConstants.js

Take care of changes requested in Nov 3 punch list 2
* Show related issues for a feature
* Comments count should be shown
* Organization name cannot have the word buildly in it
* Rich text editor for description
* Links back to original third party tool cards/issues (if available)
Closes #192

Nov 3 punch list 2

---

src/utils/validators.js

Update validator (regex pattern) check for the user email

Update validator check for the user email

---

src/pages/NewProduct/ProductFormConstants.js
src/pages/NewProduct/components/ApplicationMarket.js
src/pages/NewProduct/components/BudgetTechnology.js
src/pages/NewProduct/components/Setup.js
src/pages/NewProduct/components/TeamUser.js
src/pages/NewProduct/components/UseInfo.js

Update team role options
Change back button to outlined style
Remove validation check for team roles

Update team role options & UI improvement

---

src/pages/Dashboard/components/Report/Report.js
src/pages/NewProduct/components/TeamUser.js
src/styles/theme.js

Styling updates for tables and buttons

Styling updates for tables and buttons

---

src/pages/Register/Register.js

Add a terms of service and privacy policy checkbox

Terms of service  and privacy policy checkbox

---

package.json

_Describe the problem or feature_
_Other important information related to the ticket_
_PLAT-999_

production v0.5.6

---

package.json
src/index.html
src/index.js
src/pages/Dashboard/components/Report/Report.js

_Describe the problem or feature_
_Other important information related to the ticket_
_PLAT-999_

Update version 0.5.7

---

src/layout/TopBar/TopBar.js

Add redirect on click of the user management button

Add redirect on click of the user management button

---

src/pages/Dashboard/DashboardConstants.js

Remove description field from tabular and Kanban view
[Remove descr field from dashboard](https://github.com/buildlyio/buildly-react-template/issues/58)

Remove description field from tabular and Kanban view

---

src/pages/Dashboard/forms/AddFeatures.js

Update the list of required fields on the features form
Update the saving logic to include status, priority and tags when creating a feature
[The description fields on the second to last tab of the wizard should be optional](https://github.com/buildlyio/buildly-react-template/issues/59)

Features form improvements

---

src/layout/TopBar/TopBar.js
src/pages/Dashboard/forms/AddFeatures.js
src/pages/Dashboard/forms/AddIssues.js

Hide estimate & complexity fields when creating an issue
Show estimate & complexity fields when editing an issue, disable the fields
[When submitting a new issue hide calculated and unnecessary fields for the user](https://github.com/buildlyio/buildly-react-template/issues/62)

Issues form improvements

---

src/layout/TopBar/TopBar.js
src/pages/UserProfile/Subscriptions/Subscriptions.js

Update dropdown option label
List product name on the subscriptions table

Strip integration updates

---

src/pages/Register/Register.js

Enable to coupon field (registration form)

Enable to coupon field (registration form)

---

src/pages/Dashboard/forms/AddIssues.js

Make the feature field an autocomplete field
Issue: https://github.com/buildlyio/buildly-react-template/issues/60

Issues form improvements: Make the feature field an autocomplete field

---

src/layout/TopBar/TopBar.js
src/pages/UserProfile/Subscriptions/Subscriptions.js

Subscription improvements
Show renew subscription button against the expired subscription
Disable release button if there are no active subscriptions

Subscription improvements

---

src/pages/Dashboard/Dashboard.js

Update user actions on login for a new user
Issue: https://github.com/buildly-release-management/buildly-react-template/issues/228#event-8965186299

Update user actions on login for a new user

---

src/pages/Dashboard/forms/IssueSuggestions.js

Change feature field "issue_suggestions" to "suggested_issues" to adopt the new BE changes

change issue_suggestions to suggested_issues

---

src/pages/Roadmap/components/Report/Report.js

Add options from the Download PDF button: Download or Send

Add options from the Download PDF button: Download or Send

---

src/pages/NewProduct/components/ProductSetup.js
src/pages/NewProduct/components/UseInfo.js

Product wizard: Make descriptive fields in the wizard optional

Product wizard: Make descriptive fields in the wizard optional

---

src/modules/release/details/ReleaseDetails.css
src/modules/release/details/ReleaseDetails.tsx
src/modules/release/list/ReleaseList.tsx
src/pages/Roadmap/Roadmap.js

UI clean up

---

src/pages/Roadmap/forms/AddFeatures.js

Add complexity and release_uuid fields to the feature form

Add complexity and release_uuid fields to the feature form

---

src/pages/Roadmap/Roadmap.js
src/pages/Roadmap/components/Tabular.js
src/pages/Roadmap/forms/AddFeatures.js
src/redux/release/actions/release.actions.js
src/redux/release/actions/release.actions.test.js
src/redux/release/sagas/release.saga.js

Update a release's complexity and release
[_PLAT-999_](https://github.com/orgs/buildly-release-management/projects/2/views/4?pane=issue&itemId=42674662)

Update a release's complexity and release

---

src/pages/Roadmap/forms/AddIssues.js

Save assignees assigned to an issue
[ISSUE](https://github.com/orgs/buildly-release-management/projects/2/views/4?pane=issue&itemId=42673279)

Save assignees assigned to an issue

---

src/pages/NewProduct/components/Setup.js

Make timezone field an autocomplete select

Make timezone field an autocomplete select

---

src/modules/release/details/ReleaseDetails.tsx
src/modules/release/list/ReleaseList.tsx

List release features

---

src/modules/release/details/ReleaseDetails.tsx
src/modules/release/list/ReleaseList.tsx
src/pages/Roadmap/forms/AddIssues.js

List features issues

---

src/modules/release/list/ReleaseList.tsx
src/pages/Roadmap/forms/AddIssues.js

Releases list fixes

---

src/modules/release/details/components/ReleaseForm.tsx
src/modules/release/list/ReleaseList.tsx

Order releases by release date
Set the release date field as mandatory
[_Other important information related to the ticket_](https://github.com/buildly-release-management/buildly-react-template/issues/255)

Order releases by release date

---

src/pages/Roadmap/components/Kanban.js
yarn-error.log

Kanban: Dragging first item to an empty swimlane
Kanban: Dragging first item to an empty swimlane
[246](https://github.com/buildly-release-management/buildly-react-template/issues/246)

Kanban: Dragging first item to an empty swimlane

---

src/pages/Roadmap/forms/Comments.js
src/redux/release/sagas/release.saga.js

To add commenter user information in issue/feature of Kanban
Nothing
#278

Commenter user info added - #278

---

src/pages/Roadmap/components/Report/Report.js

Email pdf report
Email pdf report

Email pdf report

---

package.json
src/pages/Insights/utils.js
src/redux/coreuser/coreuser.saga.js

Fix budget

---

src/pages/Insights/Insights.js
src/pages/Insights/utils.js

refactor report data

---

src/components/Chatbot/Chatbot.css
src/components/Chatbot/Chatbot.js
src/index.js
src/modules/release/details/ReleaseDetails.tsx
src/modules/release/list/ReleaseList.tsx
src/pages/Insights/Insights.js
src/pages/NewProduct/NewProduct.js
src/pages/ProductPortfolio/ProductPortfolio.js
src/pages/ProductRoadmap/ProductRoadmap.js

Move the API to BabbleBeaver BE

Chatbot changes

---

src/layout/TopBar/TopBar.js
src/modules/release/list/ReleaseList.tsx
src/pages/ProductRoadmap/components/Kanban.js
src/pages/UserProfile/Subscriptions/Subscriptions.js

Add logic to cancel a subscription
Add logic to cancel a subscription

Subscription enhancements

---

src/pages/ProductRoadmap/forms/IssueSuggestions.js

Suggested issue display changes

---

src/pages/ProductRoadmap/forms/AddFeatures.js
src/redux/release/actions/release.actions.js
src/redux/release/reducers/release.reducer.js
src/redux/release/sagas/release.saga.js

User story changes

---

src/pages/NewProduct/components/ApplicationMarket.js
src/pages/ProductRoadmap/forms/AddFeatures.js
src/redux/release/actions/release.actions.js
src/redux/release/reducers/release.reducer.js
src/redux/release/sagas/release.saga.js

Add user profile input in the product form
Ability to provide user profiles while setting up user types in product form. This in turn is used for suggesting user stories from the backend system.
Closes #316

Add user profile

---

src/App.js
src/layout/TopBar/TopBar.js
src/pages/RegistrationFinish/RegistrationFinish.css
src/pages/RegistrationFinish/RegistrationFinish.js
src/pages/UserProfile/Subscriptions/Subscriptions.js
src/react-query/mutations/authUser/addSubscriptionMutation.js
src/react-query/mutations/authUser/loginMutation.js
src/routes/routesConstants.js
src/utils/registration.js

Finish registration & subscription re-activation

Finish registration & subscription re-activation

---

src/pages/Register/Register.js

User registration logic enhancements

User registration logic enhancements

---

src/pages/RegistrationFinish/RegistrationFinish.css
src/pages/RegistrationFinish/RegistrationFinish.js
src/pages/UserProfile/Subscriptions/Subscriptions.js
src/pages/UserProfile/UserProfile.js
src/react-query/mutations/authUser/loginMutation.js

Show subscription tab if user is orgAdmin
Show subscription tab if user is orgAdmin

Show subscription tab if user is orgAdmin

---

src/pages/ProductRoadmap/components/Kanban.js
src/pages/ProductRoadmap/forms/StatusBoard.js

Order board statuses
Order board statuses

Order board statuses

---

src/components/Charts/BarChart/BarChart.js
src/components/DataTableWrapper/DataTableWrapper.js
src/components/SearchInput/SearchInput.css
src/components/SearchInput/SearchInput.js
src/components/StripeCard/StripeCard.js
src/modules/oauth/oauth.service.js
src/pages/ProductRoadmap/ProductRoadmap.js
src/pages/ProductRoadmap/components/Kanban.js
src/pages/ProductRoadmap/components/Tabular.js
src/pages/Register/Register.js
src/pages/ReleaseDetails/ReleaseDetails.js
src/pages/ReleaseDetails/components/ReleaseForm.js
src/pages/ReleaseList/ReleaseList.js
src/pages/UserManagement/UserManagement.js
src/pages/UserManagement/UserManagementStyles.css
src/pages/UserManagement/forms/AddUser.js
src/utils/validators.js
src/zustand/product/productStore.js

- Credit card error
- Tabular view cache issue
- Filters do not for the user session
- No indication to check email and confirm account
- Kanban lanes do not retain order
- Go with suggestions
Closes #357 
Closes #356 
Closes #355 
Closes #353 
Closes #352 
Closes #348

Fixes from punchlist 0.10.0

---

src/pages/ProductRoadmap/components/Kanban.js

Kanban view updates
Group a feature and its issues together

Kanban updates
